### ISSUE TITLE
Test in `conda build rdkit` fails in Ubuntu 14.04

### ISSUE THREAD

**Issue by delta2323** [rdkit/conda-rdkit#46]
I followed the instruction in README and encountered the following error when I ran `conda build rdkit`. Let me know what kind of information is needed for investigation. Thanks in advance.

Environment:
* Ubuntu 14.04
* Use pyenv to install anaconda3 with conda 4.3.14

```
The following tests FAILED:
         42 - testMolWriter (SEGFAULT)
        111 - pythonTestDirML (Failed)
Errors while running CTest
Traceback (most recent call last):
  File "/home/delta/.pyenv/versions/anaconda3-4.3.0/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/delta/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "/home/delta/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "/home/delta/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/home/delta/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda_build/build.py", line 1493, in build_tree
    config=config)
  File "/home/delta/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda_build/build.py", line 1132, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/home/delta/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda_build/utils.py", line 611, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/home/delta/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda_build/utils.py", line 607, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/home/delta/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/home/delta/.pyenv/versions/anaconda3-4.3.0/conda-bld/rdkit_1488846112051/work/conda_build.sh']' returned non-zero exit status 8.
```

**Comment by greglandrum** [comment]
The conda builds use a release version of the RDKit. Python 3.6 support was added in github, but has not been released. The conda builds should support python3.6 when the 2017.03 release is done (should happen in the next month).
In the meantime, if you switch to python 3.5, I would expect everything to work.

**Comment by delta2323** [comment]
Thanks, I understand it. Should we close this issue by myself, or you close it?

**Comment by greglandrum** [comment]
It's fine for you to close it, but since I'm here anyway I will do so.

**Comment by delta2323** [comment]
Thank you
