### ISSUE TITLE
Conda Docker build fails

### ISSUE THREAD

**Issue by markussitzmann** [rdkit/conda-rdkit#50]
Hi,

If I checkout and either use master or develop, the Docker build ("docker build .") breaks (Docker runs on Fedora):

**[...]**
[100%] Built target rdMolDescriptors
[100%] Linking CXX shared module ../../../../rdkit/Chem/rdChemReactions.so
[100%] Built target rdChemReactions
[100%] Linking CXX executable testReaction
[100%] Built target testReaction
++ uname
+ [[ Linux == \L\i\n\u\x ]]
+ RDBASE=/home/rdkit/bld/rdkit_1494777495800/work
+ LD_LIBRARY_PATH=/home/rdkit/bld/rdkit_1494777495800/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib:/home/rdkit/bld/rdkit_1494777495800/work/lib
+ PYTHONPATH=/home/rdkit/bld/rdkit_1494777495800/work
+ ctest -j4 --output-on-failure
Test project /home/rdkit/bld/rdkit_1494777495800/work
        Start   1: testInchi
        Start   2: testAvalonLib1
        Start   3: pyAvalonTools
        Start   4: testDict
  1/118 Test   #3: pyAvalonTools ......................   Passed    0.19 sec
        Start   5: testRDValue
  2/118 Test   #5: testRDValue ........................   Passed    0.30 sec
        Start   6: testDataStructs
  3/118 Test   #6: testDataStructs ....................   Passed    0.20 sec
        Start   7: testFPB
  4/118 Test   #7: testFPB ............................   Passed    0.30 sec
        Start   8: testMultiFPB
  5/118 Test   #8: testMultiFPB .......................   Passed    0.01 sec
        Start   9: pyBV
  6/118 Test   #9: pyBV ...............................   Passed    0.42 sec
        Start  10: pyDiscreteValueVect
  7/118 Test   #4: testDict ...........................   Passed    2.53 sec
  8/118 Test  #10: pyDiscreteValueVect ................   Passed    0.30 sec
        Start  11: pySparseIntVect
        Start  12: pyFPB
  9/118 Test  #11: pySparseIntVect ....................   Passed    0.20 sec
        Start  13: testTransforms
 10/118 Test  #12: pyFPB ..............................   Passed    0.30 sec
 11/118 Test  #13: testTransforms .....................   Passed    0.20 sec
        Start  14: testGrid
        Start  15: testPyGeometry
 12/118 Test  #14: testGrid ...........................   Passed    0.11 sec
 13/118 Test  #15: testPyGeometry .....................   Passed    0.12 sec
        Start  16: testMatrices
        Start  17: testAlignment
 14/118 Test  #17: testAlignment ......................   Passed    0.10 sec
 15/118 Test  #16: testMatrices .......................   Passed    0.20 sec
        Start  18: pyAlignment
        Start  19: testOptimizer
 16/118 Test  #19: testOptimizer ......................   Passed    0.10 sec
 17/118 Test  #18: pyAlignment ........................   Passed    0.20 sec
        Start  20: testUFFForceField
        Start  21: testMMFFForceField
 18/118 Test  #20: testUFFForceField ..................   Passed    0.11 sec
        Start  22: pyForceFieldConstraints
 19/118 Test  #22: pyForceFieldConstraints ............   Passed    0.91 sec
 20/118 Test   #1: testInchi ..........................   Passed    4.99 sec
        Start  23: testDistGeom
        Start  24: pyDistGeom
 21/118 Test  #24: pyDistGeom .........................   Passed    0.10 sec
 22/118 Test  #23: testDistGeom .......................   Passed    0.10 sec
        Start  25: graphmolTest1
        Start  26: graphmolcpTest
 23/118 Test  #26: graphmolcpTest .....................   Passed    0.10 sec
 24/118 Test  #25: graphmolTest1 ......................   Passed    0.10 sec
        Start  27: graphmolqueryTest
        Start  28: graphmolMolOpsTest
 25/118 Test  #27: graphmolqueryTest ..................   Passed    0.20 sec
        Start  29: graphmoltestCanon
 26/118 Test  #29: graphmoltestCanon ..................   Passed    0.20 sec
        Start  30: graphmoltestChirality
 27/118 Test  #30: graphmoltestChirality ..............   Passed    0.20 sec
        Start  31: graphmoltestPickler
 28/118 Test  #28: graphmolMolOpsTest .................   Passed    1.05 sec
 29/118 Test  #31: graphmoltestPickler ................   Passed    0.22 sec
        Start  32: graphmoltestPicklerGlobalSetting
        Start  33: graphmolIterTest
 30/118 Test  #32: graphmoltestPicklerGlobalSetting ...   Passed    0.10 sec
 31/118 Test  #33: graphmolIterTest ...................   Passed    0.20 sec
        Start  34: hanoiTest
        Start  35: graphmolMemTest1
 32/118 Test  #35: graphmolMemTest1 ...................   Passed    0.20 sec
        Start  36: resMolSupplierTest
 33/118 Test  #36: resMolSupplierTest .................   Passed    1.11 sec
        Start  37: testDepictor
 34/118 Test  #37: testDepictor .......................   Passed    0.30 sec
        Start  38: pyDepictor
 35/118 Test  #38: pyDepictor .........................   Passed    0.60 sec
        Start  39: smiTest1
 36/118 Test  #39: smiTest1 ...........................   Passed    0.30 sec
        Start  40: cxsmilesTest
 37/118 Test  #40: cxsmilesTest .......................   Passed    0.20 sec
        Start  41: smaTest1
 38/118 Test  #41: smaTest1 ...........................   Passed    1.11 sec
        Start  42: fileParsersTest1
 39/118 Test  #21: testMMFFForceField .................   Passed    8.44 sec
        Start  43: testMolSupplier
 40/118 Test  #43: testMolSupplier ....................   Passed    0.40 sec
        Start  44: testMolWriter
 41/118 Test  #44: testMolWriter ......................   Passed    0.40 sec
        Start  45: testTplParser
 42/118 Test  #45: testTplParser ......................   Passed    0.02 sec
        Start  46: testMol2ToMol
 43/118 Test  #46: testMol2ToMol ......................   Passed    0.04 sec
        Start  47: testSequence
 44/118 Test  #47: testSequence .......................   Passed    0.05 sec
        Start  48: testSubstructMatch
 45/118 Test   #2: testAvalonLib1 .....................   Passed   14.73 sec
        Start  49: testReaction
 46/118 Test  #48: testSubstructMatch .................   Passed    0.71 sec
 47/118 Test  #49: testReaction .......................   Passed    0.41 sec
        Start  50: testReactionFingerprints
        Start  51: testEnumeration
 48/118 Test  #50: testReactionFingerprints ...........   Passed    0.03 sec
 49/118 Test  #51: testEnumeration ....................   Passed    0.23 sec
        Start  52: pyChemReactions
        Start  53: pyChemReactionEnumerations
 50/118 Test  #52: pyChemReactions ....................   Passed    0.30 sec
        Start  54: pyChemReactionSanitize
 51/118 Test  #54: pyChemReactionSanitize .............   Passed    0.16 sec
        Start  55: testChemTransforms
 52/118 Test  #55: testChemTransforms .................   Passed    0.31 sec
        Start  56: testSubgraphs1
 53/118 Test  #53: pyChemReactionEnumerations .........   Passed    1.05 sec
        Start  57: testSubgraphs2
 54/118 Test  #57: testSubgraphs2 .....................   Passed    0.01 sec
 55/118 Test  #56: testSubgraphs1 .....................   Passed    0.39 sec
        Start  58: filterCatalogTest
        Start  59: pyFilterCatalog
 56/118 Test  #58: filterCatalogTest ..................   Passed    0.40 sec
        Start  60: testFragCatalog
 57/118 Test  #59: pyFilterCatalog ....................   Passed    1.01 sec
        Start  61: pyFragCatalog
 58/118 Test  #60: testFragCatalog ....................   Passed    0.50 sec
 59/118 Test  #61: pyFragCatalog ......................   Passed    0.20 sec
        Start  62: testDescriptors
        Start  63: testPBF
 60/118 Test  #63: testPBF ............................   Passed    0.30 sec
        Start  64: test3D
 61/118 Test  #64: test3D .............................   Passed    0.92 sec
        Start  65: pyMolDescriptors
 62/118 Test  #65: pyMolDescriptors ...................   Passed    0.52 sec
        Start  66: testFingerprints
 63/118 Test  #62: testDescriptors ....................   Passed    3.66 sec
        Start  67: testPartialCharges
 64/118 Test  #67: testPartialCharges .................   Passed    0.04 sec
        Start  68: pyPartialCharges
 65/118 Test  #68: pyPartialCharges ...................   Passed    0.32 sec
        Start  69: testMolTransforms
 66/118 Test  #69: testMolTransforms ..................   Passed    0.04 sec
        Start  70: pyMolTransforms
 67/118 Test  #42: fileParsersTest1 ...................   Passed   12.46 sec
        Start  71: testMMFFForceFieldHelpers
 68/118 Test  #70: pyMolTransforms ....................   Passed    0.32 sec
        Start  72: testUFFForceFieldHelpers
 69/118 Test  #66: testFingerprints ...................   Passed    8.58 sec
        Start  73: testCrystalForceField
 70/118 Test  #73: testCrystalForceField ..............   Passed    0.05 sec
        Start  74: pyForceFieldHelpers
 71/118 Test  #74: pyForceFieldHelpers ................   Passed    0.42 sec
 72/118 Test  #34: hanoiTest ..........................   Passed   23.39 sec
        Start  75: testDistGeomHelpers
        Start  76: pyDistGeom
 73/118 Test  #76: pyDistGeom .........................   Passed    5.56 sec
        Start  77: testMolAlign
 74/118 Test  #71: testMMFFForceFieldHelpers ..........   Passed   17.79 sec
        Start  78: pyMolAlign
 75/118 Test  #72: testUFFForceFieldHelpers ...........   Passed   20.72 sec
        Start  79: testFeatures
 76/118 Test  #79: testFeatures .......................   Passed    0.20 sec
        Start  80: pyChemicalFeatures
 77/118 Test  #80: pyChemicalFeatures .................   Passed    0.25 sec
        Start  81: testShapeHelpers
 78/118 Test  #81: testShapeHelpers ...................   Passed    0.22 sec
        Start  82: pyShapeHelpers
 79/118 Test  #82: pyShapeHelpers .....................   Passed    0.29 sec
        Start  83: testMolCatalog
 80/118 Test  #83: testMolCatalog .....................   Passed    0.21 sec
        Start  84: pyMolCatalog
 81/118 Test  #84: pyMolCatalog .......................   Passed    0.29 sec
        Start  85: moldraw2DTest1
 82/118 Test  #85: moldraw2DTest1 .....................   Passed    2.62 sec
        Start  86: pyMolDraw2D
 83/118 Test  #86: pyMolDraw2D ........................   Passed    0.26 sec
        Start  87: testFMCS
 84/118 Test  #87: testFMCS ...........................   Passed    1.42 sec
        Start  88: pyFMCS
 85/118 Test  #88: pyFMCS .............................   Passed    1.42 sec
        Start  89: FMCStest
 86/118 Test  #89: FMCStest ...........................   Passed    0.21 sec
        Start  90: testMolHash
 87/118 Test  #90: testMolHash ........................   Passed    0.21 sec
        Start  91: pyMolHash
 88/118 Test  #91: pyMolHash ..........................   Passed    0.23 sec
        Start  92: testMMPA
 89/118 Test  #92: testMMPA ...........................   Passed    0.21 sec
        Start  93: pyMMPA
 90/118 Test  #78: pyMolAlign .........................   Passed   14.35 sec
 91/118 Test  #93: pyMMPA .............................   Passed    1.74 sec
        Start  94: testStructChecker
        Start  95: pyStructChecker
 92/118 Test  #94: testStructChecker ..................   Passed    0.10 sec
 93/118 Test  #95: pyStructChecker ....................   Passed    0.15 sec
        Start  96: testReducedGraphs
        Start  97: pyReducedGraphs
 94/118 Test  #97: pyReducedGraphs ....................   Passed    0.12 sec
 95/118 Test  #96: testReducedGraphs ..................   Passed    0.12 sec
        Start  98: trajectoryTest
        Start  99: testSLNParse
 96/118 Test  #98: trajectoryTest .....................   Passed    0.16 sec
 97/118 Test  #99: testSLNParse .......................   Passed    0.16 sec
        Start 100: pySLNParse
        Start 101: pyGraphMolWrap
 98/118 Test #100: pySLNParse .........................   Passed    0.20 sec
        Start 102: pyTestConformerWrap
 99/118 Test #102: pyTestConformerWrap ................   Passed    0.20 sec
        Start 103: pyTestTrajectory
100/118 Test #103: pyTestTrajectory ...................   Passed    0.60 sec
        Start 104: pyTestThreads
101/118 Test #104: pyTestThreads ......................   Passed    1.45 sec
        Start 105: testQuery
102/118 Test #105: testQuery ..........................   Passed    0.30 sec
        Start 106: testMatCalc
103/118 Test #106: testMatCalc ........................   Passed    0.21 sec
        Start 107: pyMatCalc
104/118 Test #107: pyMatCalc ..........................   Passed    0.50 sec
        Start 108: pySimDivPickers
105/118 Test #108: pySimDivPickers ....................   Passed    3.02 sec
        Start 109: pyRanker
106/118 Test #109: pyRanker ...........................   Passed    0.14 sec
        Start 110: testChemicalFeatures
107/118 Test #110: testChemicalFeatures ...............   Passed    0.30 sec
        Start 111: pyFeatures
108/118 Test #111: pyFeatures .........................   Passed    0.30 sec
        Start 112: pythonTestDbCLI
109/118 Test #101: pyGraphMolWrap .....................   Passed    8.75 sec
        Start 113: pythonTestDirML
110/118 Test #113: pythonTestDirML ....................   Passed    6.53 sec
        Start 114: pythonTestDirDataStructs
111/118 Test #114: pythonTestDirDataStructs ...........   Passed    0.91 sec
        Start 115: pythonTestDirDbase
112/118 Test #115: pythonTestDirDbase .................   Passed    0.50 sec
        Start 116: pythonTestDirSimDivFilters
113/118 Test #116: pythonTestDirSimDivFilters .........   Passed    0.19 sec
        Start 117: pythonTestDirVLib
114/118 Test #117: pythonTestDirVLib ..................   Passed    0.51 sec
        Start 118: pythonTestDirChem
115/118 Test #112: pythonTestDbCLI ....................   Passed   12.67 sec
116/118 Test  #75: testDistGeomHelpers ................   Passed   52.92 sec
117/118 Test  #77: testMolAlign .......................   Passed   78.98 sec
118/118 Test #118: pythonTestDirChem ..................***Failed   40.60 sec
Errors while running CTest
....
----------------------------------------------------------------------
Ran 4 tests in 0.031s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.031s

OK
....[16:07:34] 

****
Pre-condition Violation
valence not defined for atoms not associated with molecules
Violation occurred on line 267 in file /home/rdkit/bld/rdkit_1494777495800/work/Code/GraphMol/Atom.cpp
Failed Expression: dp_mol
****

.
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.006s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.007s

OK
......................
----------------------------------------------------------------------
Ran 22 tests in 0.025s

OK
.....s.................ss
----------------------------------------------------------------------
Ran 25 tests in 0.102s

OK (skipped=3)
..s
----------------------------------------------------------------------
Ran 3 tests in 0.125s

OK (skipped=1)
...................................
----------------------------------------------------------------------
Ran 35 tests in 1.056s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.013s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.007s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.025s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.045s

OK
.ss.ss.......
----------------------------------------------------------------------
Ran 13 tests in 0.786s

OK (skipped=4)
...[16:07:38] WARNING: More than one matching pattern found - picking one
[16:07:38] WARNING: More than one matching pattern found - picking one
.[16:07:38] WARNING: More than one matching pattern found - picking one
..
----------------------------------------------------------------------
Ran 6 tests in 0.061s

OK
........
----------------------------------------------------------------------
Ran 8 tests in 0.084s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 3.380s

OK
[16:07:42] WARNING: Omitted undefined stereo
[16:07:42] WARNING: Proton(s) added/removed
.....
----------------------------------------------------------------------
Ran 5 tests in 8.343s

OK

InChI write Summary: 1164 identical, 0 suffix variance, 17 reasonable

InChI read Summary: 620 identical, 0 variance, 561 reasonable variance
....
----------------------------------------------------------------------
Ran 4 tests in 2.088s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.286s

OK
Traceback (most recent call last):
  File "UnitTestPandasTools.py", line 12, in <module>
    from rdkit.Chem import PandasTools
  File "/home/rdkit/bld/rdkit_1494777495800/work/rdkit/Chem/PandasTools.py", line 154, in <module>
    from pandas.core import format as fmt  # older versions
ImportError: cannot import name format
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
UnitTestDocTestsChem.py:5: DeprecationWarning: The rdkit.Chem.MCS module is deprecated; please use rdkit.Chem.rdFMCS instead.
  from rdkit.Chem import MCS, FragmentMatcher, MACCSkeys, Descriptors, TemplateAlign
/home/rdkit/bld/rdkit_1494777495800/work/rdkit/Chem/MCS.py:1: DeprecationWarning: The rdkit.Chem.MCS module is deprecated; please use rdkit.Chem.rdFMCS instead.
  # This work was funded by Roche and generously donated to the free
.............[16:07:55] WARNING: More than one matching pattern found - picking one
[16:07:55] WARNING: More than one matching pattern found - picking one
........
----------------------------------------------------------------------
Ran 21 tests in 0.731s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.061s

OK
..................
----------------------------------------------------------------------
Ran 18 tests in 0.837s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.073s

OK
........
----------------------------------------------------------------------
Ran 8 tests in 0.019s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.014s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.011s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.056s

OK
........
----------------------------------------------------------------------
Ran 8 tests in 0.001s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.004s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.001s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.003s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.009s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.012s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 2.571s

OK
..........
----------------------------------------------------------------------
Ran 10 tests in 0.037s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
..........
----------------------------------------------------------------------
Ran 10 tests in 0.004s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.051s

OK
.....................
----------------------------------------------------------------------
Ran 21 tests in 3.186s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
...[16:08:05] 

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 37 in file /home/rdkit/bld/rdkit_1494777495800/work/Code/GraphMol/MolChemicalFeatures/MolChemicalFeature.cpp
Failed Expression: dp_mol->getNumConformers()
****

.
----------------------------------------------------------------------
Ran 4 tests in 0.018s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 6.986s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.075s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.008s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.015s

OK
..........
----------------------------------------------------------------------
Ran 10 tests in 0.278s

OK
ssssss...s.....
----------------------------------------------------------------------
Ran 15 tests in 0.159s

OK (skipped=7)
s
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK (skipped=1)
..........
----------------------------------------------------------------------
Ran 10 tests in 0.425s

OK
..[16:08:14] reaction has no reactants
[16:08:14] reaction has no products
[16:08:14] initialization failed
[16:08:14] reaction has no reactants
[16:08:14] reaction has no products
.
----------------------------------------------------------------------
Ran 3 tests in 0.020s

OK
................[16:08:14] ERROR: 
[16:08:14] ERROR: 
.
----------------------------------------------------------------------
Ran 17 tests in 0.026s

OK
!!! TEST FAILURE:  python UnitTestPandasTools.py {}
Exception TypeError: "'NoneType' object is not callable" in <function _removeHandlerRef at 0x7f4b48a6b668> ignored

99% tests passed, 1 tests failed out of 118

Total Test time (real) = 115.91 sec

The following tests FAILED:
	118 - pythonTestDirChem (Failed)
BUILD START: rdkit-__conda_version__-np111py27_1
    (actual version deferred until further download or env creation)

The following NEW packages will be INSTALLED:

    boost:           1.56.0-py27_3      local
    bzip2:           1.0.6-3                 
    cairo:           1.14.6-nox_0       local [nox]
    cmake:           3.6.3-0                 
    curl:            7.52.1-0                
    eigen:           3.2.8-2            local
    expat:           2.1.0-0                 
    fontconfig:      2.11.1-6                
    freetype:        2.5.5-2                 
    jbig:            2.1-0                   
    jpeg:            9b-0                    
    libiconv:        1.14-0                  
    libpng:          1.6.27-0                
    libtiff:         4.0.6-3                 
    libxml2:         2.9.4-0                 
    mkl:             2017.0.1-0              
    ncurses:         5.9-10                  
    nox:             1.0-0              local
    numpy:           1.11.3-py27_0           
    olefile:         0.44-py27_0             
    openssl:         1.0.2k-2                
    pandas:          0.20.1-np111py27_0      
    pillow:          4.1.1-py27_0            
    pip:             9.0.1-py27_1            
    pixman:          0.32.6-0                
    pkg-config:      0.28-1                  
    python:          2.7.13-0                
    python-dateutil: 2.6.0-py27_0            
    pytz:            2017.2-py27_0           
    readline:        6.2-2                   
    requests:        2.14.2-py27_0           
    setuptools:      27.2.0-py27_0           
    six:             1.10.0-py27_0           
    sqlite:          3.13.0-0                
    tk:              8.5.18-0                
    wheel:           0.29.0-py27_0           
    xz:              5.2.2-1                 
    zlib:            1.2.8-3                 

Applying patch: u'/home/rdkit/conda-rdkit/rdkit/rdpaths.patch'
Patch level ambiguous, selecting least deep
BUILD START (revised): rdkit-__conda_version__-np111py27_1
Package: rdkit-__conda_version__-np111py27_1
source tree in: /home/rdkit/bld/rdkit_1494777495800/work
Traceback (most recent call last):
  File "/home/rdkit/miniconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/rdkit/miniconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 334, in main
    execute(sys.argv[1:])
  File "/home/rdkit/miniconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 325, in execute
    noverify=args.no_verify)
  File "/home/rdkit/miniconda/lib/python2.7/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/home/rdkit/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 1518, in build_tree
    config=config)
  File "/home/rdkit/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 1143, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/home/rdkit/miniconda/lib/python2.7/site-packages/conda_build/utils.py", line 628, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/home/rdkit/miniconda/lib/python2.7/site-packages/conda_build/utils.py", line 624, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/home/rdkit/miniconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/home/rdkit/bld/rdkit_1494777495800/work/conda_build.sh']' returned non-zero exit status 8
The command '/bin/sh -c conda build boost --quiet --no-anaconda-upload &&     conda build nox --quiet --no-anaconda-upload &&     conda build cairo_nox --quiet --no-anaconda-upload &&     conda build cairocffi --quiet --no-anaconda-upload &&     conda build eigen --quiet --no-anaconda-upload &&     conda build rdkit --quiet --no-anaconda-upload &&     conda build ncurses --quiet --no-anaconda-upload &&     conda build postgresql --quiet --no-anaconda-upload &&     conda build rdkit-postgresql --quiet --no-anaconda-upload &&     conda build postgresql95 --quiet --no-anaconda-upload &&     conda build rdkit-postgresql95 --quiet --no-anaconda-upload &&     CONDA_PY=35 conda build boost --quiet --no-anaconda-upload &&     CONDA_PY=35 conda build nox --quiet --no-anaconda-upload &&     CONDA_PY=35 conda build cairo_nox --quiet --no-anaconda-upload &&     CONDA_PY=35 conda build cairocffi --quiet --no-anaconda-upload &&     CONDA_PY=35 conda build eigen --quiet --no-anaconda-upload &&     CONDA_PY=35 conda build rdkit --quiet --no-anaconda-upload &&     CONDA_PY=35 conda build postgresql --quiet --no-anaconda-upload &&     CONDA_PY=35 conda build rdkit-postgresql --quiet --no-anaconda-upload &&     CONDA_PY=35 conda build postgresql95 --quiet --no-anaconda-upload &&     CONDA_PY=35 conda build rdkit-postgresql95 --quiet --no-anaconda-upload &&     CONDA_NPY=110 conda build rdkit --quiet --no-anaconda-upload &&     CONDA_PY=35 CONDA_NPY=110 conda build rdkit --quiet --no-anaconda-upload' returned a non-zero code: 1
[sitzmann@green conda-rdkit]$

**Comment by greglandrum** [comment]
This is caused by backwards-incompatible changes that were made in v0.20 of pandas.
It's been fixed on master and will be part of the 2017_03_2 release, which will fix the conda builds.
In the meantime you could downgrade pandas to v0.19 (either manually or by specifying a version < 0.20 in `rdkit/meta.yaml`) and things should be fine.

**Comment by markussitzmann** [comment]
Thanks, Greg!
